webpages = [
    "https://nps.gov/romo/planyourvisit/hikes.htm",
    "https://www.nps.gov/romo/learn/nature/animals.htm",
    "https://www.nps.gov/romo/planyourvisit/fees.htm",
    "https://www.nps.gov/romo/plan-your-summer-trip-to-rocky.htm",
    "https://www.nps.gov/romo/plan-your-fall-trip-to-rocky.htm",
    "https://www.nps.gov/romo/planyourvisit/plan-your-winter-springtime-visit-to-rocky.htm",
    "https://www.nps.gov/romo/planyourvisit/placestogo.htm",
    "https://www.nps.gov/romo/planyourvisit/visitorcenters.htm",
    "https://www.nps.gov/rlc/continentaldivide/wildlife.htm",
    "https://www.nps.gov/romo/planyourvisit/timed-entry-permit-system.htm",
    "https://www.colorado.com/articles/rocky-mountain-national-park-itinerary",
    "https://www.earthtrekkers.com/rocky-mountain-national-park-itinerary/",
    "https://www.danae-explore.com/en/post/4-days-in-rocky-mountain-national-park",
    "https://storyateverycorner.com/rocky-mountain-national-park-itinerary-in-summer/",
    "https://gatherandgotravel.com/glacier-itinerary/",
    "https://www.glacierparkcollection.com/glacier-national-park/stories/glacier-national-park-itineraries/",
]